package GameLogic;

public enum Structure {
	DWELLING,
	TRADINGPOST,
	TEMPLE,
	SANCTUARY,
	STRONGHOLD,
	EMPTY;

	public static Structure[] STRUCTURES_INDEXED = 
	new Structure[] {DWELLING,TRADINGPOST,TEMPLE,SANCTUARY,STRONGHOLD,EMPTY};
}